name: Docker - Latest

on:
  pull_request: null
  push:

jobs:
  build-latest:
    name: Build latest version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        base-image:
            #- "alpine"
            - "debian-slim"
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        working-directory: ${{ matrix.base-image }}
        run: |
          docker build \
          --pull \
          --no-cache \
          --tag edorian/tideways-daemon:latest \
          --tag edorian/tideways-daemon:latest-${{ matrix.base-image }} \
          --tag edorian/tideways-daemon:$(grep -P "^ENV TIDEWAYS_DAEMON_VERSION" Dockerfile | grep -oP "\d\.\d+\.\d+") \
          --tag edorian/tideways-daemon:$(grep -P "^ENV TIDEWAYS_DAEMON_VERSION" Dockerfile | grep -oP "\d\.\d+\.\d+")-${{ matrix.base-image }} \
          .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push base image specific tags to Docker Hub
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ matrix.version }}
        run: |
          docker push edorian/tideways-daemon:latest-${{ matrix.base-image }}
          docker push edorian/tideways-daemon:$(grep -P "^ENV TIDEWAYS_DAEMON_VERSION" Dockerfile | grep -oP "\d\.\d+\.\d+")-${{ matrix.base-image }}

      - name: Push generic tags
        if: github.ref == 'refs/heads/main'
        working-directory: debian-slim #alpine
        run: |
          docker push edorian/tideways-daemon:latest
          docker push edorian/tideways-daemon:$(grep -P "^ENV TIDEWAYS_DAEMON_VERSION" Dockerfile | grep -oP "\d\.\d+\.\d+")

