name: Docker - Latest

on:
  pull_request: null
  push:

jobs:
  build-latest:
    name: Build latest version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        base-image:
            #- "alpine"
            - "debian-slim"
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        working-directory: ${{ matrix.base-image }}
        run: |
          docker build \
          --pull \
          --no-cache \
          --tag edorian/tideways-daemon:latest \
          .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ matrix.version }}
        run: |
          docker push edorian/tideways-daemon:latest
